### ISSUE TITLE
Priority field can be empty, which crashes the import

### ISSUE THREAD

**Issue by fritzrichter** [calimero-project/import-ets-xml#1]
I converted my .knxproj which was created with ETS5. The resulting XML contains elements with empty "priority" field, which in fact is required by the importer.  A potential solution would be to add an additional choose-block, which checks if the priority could be resolved OTHERWISE you set it to "Low" by default.

Another issue: The import did not work with the "Location" elements included in the final XML, I had to remove these elements completely.

**Comment by bmalinowsky** [comment]
Thanks! Priority should be fixed with cb46042. 
I currently don't know why the `location` element doesn't work for you, but it's not required for a successful import.

**Comment by calimero-project** [comment]
Latest import tests do work; if your problem persists, please re-open.
