### ISSUE TITLE
Add support for extracting device information

### ISSUE THREAD

**Issue by fritzrichter** [calimero-project/import-ets-xml#2]
Right now the extraction of group addresses is supported. It would be nice, to add support for extracting device information as well from the XML files.

To summarize what would be needed:
* Physical address of the device
* Name of the device
* Potentially meta information like description etc.

**Comment by bmalinowsky** [comment]
By which API would such device information be consumed?

Currently, the group address-related information is extracted for process communication. The device information in the .knxproj file is mainly for ETS purposes for its visual editor and programming.

**Comment by fritzrichter** [comment]
Trying to write my own KNX Bus Monitor and was thinking to use calimero as my main knx library, but digging into the XML specifics now to do it myself...

**Comment by bmalinowsky** [comment]
I understand, so basically that would be information that is shown to a user to enrich a simple individual address.

**Comment by fritzrichter** [comment]
Exactly, it could be used to translate the x.y.z notation to a human readable name. Ended up in parsing the XML myself, which is pretty straight forward with SAX / DOM.
