### ISSUE TITLE
Update to ETS5?

### ISSUE THREAD

**Issue by pfisterer** [calimero-project/import-ets-xml#3]
I'm currently experimenting with exporting ETS5 files to Openhab and found your project. Do you have any plans to update this to ETS5?

I could also contribute but I currently do have issues understanding, how ComObjectInstanceRefs work in the new format.

For instance, they are as follows:

<ComObjectInstanceRefs>
                  <ComObjectInstanceRef RefId="O-0_R-1" Links="GA-7 GA-226" />
                  <ComObjectInstanceRef RefId="O-12_R-26" Links="GA-211" />
</ComObjectInstanceRefs>

I'm not quite sure how to resolve the RefId.

Best,
Dennis

**Comment by calimero-project** [comment]
ETS versions are supported up to v5.6.4 as stated in the README. Newer versions are likely never supported as the import is now done in Java.
