### ISSUE TITLE
ETS 5.7 Support

### ISSUE THREAD

**Issue by krugertech** [calimero-project/import-ets-xml#4]
Do you have any plans to add support for ETS 5.7 ?

**Comment by bmalinowsky** [comment]
Currently not, the import is now done with the _DatapointImporter_ in [calimero-tools](https://github.com/calimero-project/calimero-tools) as new knx projects might need to be decrypted first.

**Comment by krugertech** [comment]
> 
> 
> Currently not, the import is now done with the _DatapointImporter_ in [calimero-tools](https://github.com/calimero-project/calimero-tools) as new knx projects might need to be decrypted first.

Thank you for your feedback.
